import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Providers from "./_components/common/Providers";

export const metadata: Metadata = {
  title: "Fitcentive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://i.ibb.co/d77PV1y/Logo.png" }],
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} `}>
      <body className="bg-[#001636]">
        <Providers>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
